// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcXdbsBS9k3I4eQ3UPXYKuoDPuTf9xbko',
    appId: '1:647947439741:web:a2e6d3152360390a8a2b14',
    messagingSenderId: '647947439741',
    projectId: 'projetds-35f8a',
    authDomain: 'projetds-35f8a.firebaseapp.com',
    storageBucket: 'projetds-35f8a.firebasestorage.app',
    measurementId: 'G-44CBGF5B7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3m6VAw2fQ99zYdx-hF8vKSn-DWjY2uWo',
    appId: '1:647947439741:android:9e99b336bd43f1d98a2b14',
    messagingSenderId: '647947439741',
    projectId: 'projetds-35f8a',
    storageBucket: 'projetds-35f8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqas0Tfi353GxyYaxK0tAYh7YaiImt4TM',
    appId: '1:647947439741:ios:0893543efbe407ef8a2b14',
    messagingSenderId: '647947439741',
    projectId: 'projetds-35f8a',
    storageBucket: 'projetds-35f8a.firebasestorage.app',
    iosBundleId: 'com.example.sapacetoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqas0Tfi353GxyYaxK0tAYh7YaiImt4TM',
    appId: '1:647947439741:ios:0893543efbe407ef8a2b14',
    messagingSenderId: '647947439741',
    projectId: 'projetds-35f8a',
    storageBucket: 'projetds-35f8a.firebasestorage.app',
    iosBundleId: 'com.example.sapacetoon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcXdbsBS9k3I4eQ3UPXYKuoDPuTf9xbko',
    appId: '1:647947439741:web:8a9ac5b3295d017a8a2b14',
    messagingSenderId: '647947439741',
    projectId: 'projetds-35f8a',
    authDomain: 'projetds-35f8a.firebaseapp.com',
    storageBucket: 'projetds-35f8a.firebasestorage.app',
    measurementId: 'G-T42TN9TXR6',
  );

}